config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'signup' => 'users#new'

  resources :users
  resources :trips
  resources :grouped_trips

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/trip.rb
class Trip < ApplicationRecord

  before_save :create_long_lat
  has_one :name

  scope :within_location, -> (longitude, latitude, distance_in_kms = 5) {
    where(%{
     ST_Distance(location_long_lat, 'POINT(%f %f)') < %d
    } % [longitude, latitude, distance_in_kms])
  }

  scope :within_destination, -> (longitude, latitude, distance_in_kms = 5) {
    where(%{
     ST_Distance(destination_long_lat, 'POINT(%f %f)') < %d
    } % [longitude, latitude, distance_in_kms])
  }

  enum status: {
      pending: 0,
      scheduled: 1,
      in_progress: 2,
      incomplete: 3,
      complete: 4
  }

  private

  def create_long_lat
    factory = RGeo::Geographic.simple_mercator_factory
    self.location_long_lat = factory.point(self.location_longitude, self.location_latitude)
    self.destination_long_lat = factory.point(self.destination_longitude, self.destination_latitude)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  include SessionsHelper

  before_action :logged_in_user, only: [:index, :show]

  def index
    @trips = Trip.paginate(page: page_params[:page], per_page: 10)
  end

  def show
    @trip = Trip.find_by(id: require_id)
    if @trip.nil?
      flash[:danger] = 'Trip cannot be found with that id.'
      redirect_to trips_path
    end

    @trip
  end

  private
  def require_id
    params.require(:id)
  end

  def page_params
    params.permit(:page)
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Unauthorized'
      redirect_to login_url
    end
  end
end

app/helpers/trip_helper.rb
module TripHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_trip.html.erb
<tr>
    <td><%= trip.location_name %></td>
    <td><%= trip.destination_name %></td>
    <td><%= trip.status %></td>
    <td><%= trip.time_slot %></td>
    <td><%= trip.employee_name_id %></td>
    <th><%= link_to 'View', trip_path(trip.id) %></th>
</tr>

app/views/trips/index.html.erb
<% provide(:title, 'Trips') %>
<h1 class="text-center">All Trips</h1>

<div class='row'>
    <div class='col-md-12'>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Destination</th>
                    <th>Status</th>
                    <th>Time Slot</th>
                    <th>Employee Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% if @trips.any? %>
                    <%= render @trips %>
                <% else %>
                    <tr class="text-center">
                        <td colspan="6">There are no trips!</td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate %>
    </div>
</div>

app/views/trips/show.html.erb
<header>
    <%= link_to '<< Back', trips_path, class: 'float-left' %>
    <h1>Trip ID: <%= @trip.id %></h1>
</header>

<div class="container">
    <div class="row">
        <div class="trip">
            <section class="map-display">
                <div id="map"></div>
                <script>
                    function initMap() {
                        const directionsService = new google.maps.DirectionsService();
                        const directionsRenderer = new google.maps.DirectionsRenderer();
                        const map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 10
                        });
                        calculateAndDisplayRoute(directionsService, directionsRenderer);
                        directionsRenderer.setMap(map);
                    }

                    function calculateAndDisplayRoute(directionsService, directionsRenderer) {
                        directionsService.route(
                            {
                                origin: {query: '<%= @trip.location_latitude %>, <%= @trip.location_longitude %>'},
                                destination: {query: '<%= @trip.destination_latitude %>, <%= @trip.destination_longitude %>'},
                                travelMode: 'DRIVING'
                            },
                            function(response, status) {
                                if (status === 'OK') {
                                    directionsRenderer.setDirections(response);
                                } else {
                                    window.alert('Directions request failed due to ' + status);
                                }
                            });
                    }
                </script>
                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDIN5h-pSgfZVLwhfVPDkeUrZ5oreQPOuk&callback=initMap">
                </script>
            </section>
            <section>
                <dl>
                    <dt>Pickup Location</dt>
                    <dd><%= @trip.location_name %></dd>
                    <dt>Pickup Location Co-Ordinates</dt>
                    <dd>Lat: <%= @trip.location_latitude %> - Long: <%= @trip.location_longitude %></dd>
                    <dt>Destination</dt>
                    <dd><%= @trip.destination_name %></dd>
                    <dt>Destination Co-Ordinates</dt>
                    <dd>Lat: <%= @trip.destination_latitude %> - Long: <%= @trip.destination_longitude %></dd>
                    <dt>Distance</dt>
                    <dd><%= @trip.distance %></dd>
                    <dt>Time Slot</dt>
                    <dd><%= @trip.time_slot %></dd>
                    <dt>Employee Name</dt>
                    <dd><%= @trip.employee_name_id %></dd>
                </dl>
            </section>
        </div>
    </div>
</div>