config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'signup' => 'users#new'

  resources :users
  resources :trips
  resources :grouped_trips

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :person, autosave: true
  accepts_nested_attributes_for :person

  validates :username, presence: true, uniqueness: true
  validates :person, presence: true
  validates :password, presence: true, allow_nil: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :find_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(require_id)
  end

  def edit
    @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = 'User has been successfully registered!'
      redirect_to root_url
    else
      flash[:error] = 'Failed to register the user!'
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Updated profile successfully!'
      redirect_to @user
    else
      flash[:error] = 'Failed to update your profile!'
      render 'edit'
    end
  end

  private

  def user_params
    params
        .require(:user)
        .permit(
            :username,
            :password,
            :password_confirmation,
            person_attributes: [:date_of_birth, name_attributes: [:value]]
        )
  end

  def require_id
    params.require(:id)
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Unauthorized'
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(require_id)
    redirect_to(root_url) unless current_user?(@user)
  end

  def find_user
    @user = User.find(require_id)
    return true unless @user.nil?
    flash[:error] = 'Cannot find the user'
    false
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size = 50)
    gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.person.name.value, class: "gravatar", size: size)
  end
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<h1 class="text-center">Edit Profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |u| %>
            <%= render 'shared/error_messages' %>

            <%= u.fields_for :person_attributes, @user.person do |p| %>

                <%= p.fields_for :name_attributes, @user.person.name do |n| %>
                    <%= n.label :name %>
                    <%= n.text_field :value, class: 'form-control' %>
                <% end %>

                <%= p.label :date_of_birth %>
                <%= p.date_field :date_of_birth, class: 'form-control' %>

            <% end %>

            <%= u.label :username %>
            <%= u.text_field :username, class: 'form-control' %>

            <%= u.label :password %>
            <%= u.password_field :password, class: 'form-control' %>

            <%= u.label :password_confirmation %>
            <%= u.password_field :password_confirmation, class: 'form-control' %>

            <div class="text-center">
                <%= u.submit 'Submit', class: "btn btn-primary mt-2" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |u| %>
            <%= render 'shared/error_messages' %>

            <%= u.fields_for :person_attributes do |p| %>

                <%= p.fields_for :name_attributes do |n| %>
                    <%= n.label :name %>
                    <%= n.text_field :value, class: 'form-control' %>
                <% end %>

                <%= p.label :date_of_birth %>
                <%= p.date_field :date_of_birth, class: 'form-control' %>

            <% end %>

            <%= u.label :username %>
            <%= u.text_field :username, class: 'form-control' %>

            <%= u.label :password %>
            <%= u.password_field :password, class: 'form-control' %>

            <%= u.label :password_confirmation %>
            <%= u.password_field :password_confirmation, class: 'form-control' %>

            <div class="text-center">
                <%= u.submit 'Submit', class: "btn btn-primary mt-2" %>
                <p class="mt-2">Already have an account? <%= link_to 'Sign In', login_path %></p>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.person.name.value) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.person.name.value %>
            </h1>
            <h2>
                <%= @user.person.date_of_birth %>
            </h2>
            <%= link_to 'Edit Profile', edit_user_path(:id => @user.id) %>
        </section>
    </aside>
</div>