config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'signup' => 'users#new'

  resources :users
  resources :trips
  resources :grouped_trips

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to 'Driver Groups', root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home', root_path %></li>
                <% if logged_in? %>
                    <li><%= link_to 'Grouped Trips', grouped_trips_path %></li>
                    <li><%= link_to 'Trips', trips_path %></li>
                    <li><%= link_to 'Profile', current_user %></li>
                    <li><%= link_to 'Log Out', logout_path, method: "delete" %></li>
                <% else %>
                    <li><%= link_to 'Log In', login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag 'application', media: 'all',
                                'data-turbolinks-track' => true %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>

    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>